service: fossil-marketplace
app: fossil-marketplace
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  stage: dev
  region: us-east-1

cors-config: &cors-config
  origin: '*'
  headers:
    - Content-Type
    - Authorization
    - X-Amz-Date
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - X-Api-Key

functions:
  hello:
    handler: hello.helloWorld
    events:
      - http:
          path: hello-world
          method: GET
          cors:
            <<: *cors-config
  CreateAccount:
    handler: controllers/account.createAccount
    events:
      - http:
          path: create-account
          method: POST
          cors:
            <<: *cors-config
